name: 🧪 Code Checks

on: [merge_group, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Library successfully builds
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

  tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run test:ci