name: 🧪 Code Checks

on: [merge_group, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ganglion successfully builds
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
        working-directory: ./packages/ganglion

  # tests:
  #   runs-on: ubuntu-latest
  #   name: Unit Tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 8
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: 'pnpm'

  #     - run: bun install
  #     - run: bun test